# Generated by Django 4.1.7 on 2023-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='character_age',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='character_sex',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characters',
            name='character_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
